metadata:
  name: pkger
  description: pkger
  arch: x86_64
  license: MIT
  version: 0.1.0
  url: "https://github.com/vv9k/pkger"
  git: "https://github.com/vv9k/pkger.git"
  maintainer: "vv9k"
  provides:
    - pkger
  all_images: true
  depends:
    debian:
      - libssl-dev
    rocky:
      - openssl-devel
  build_depends:
    all: [ gcc, pkg-config]
    rocky+arch: [ cargo ]
    rocky: [ openssl-devel ]
    debian: [ curl, libssl-dev]
env:
  RUSTUP_URL: https://sh.rustup.rs
configure:
  steps:
    - cmd: curl -o /tmp/install_rust.sh  $RUSTUP_URL
      images: ["debian"]
    - cmd: sh /tmp/install_rust.sh -y --default-toolchain stable
      images: ["debian"]
build:
  steps:
    - cmd: cargo build --color=never
      images: ["rocky", "arch"]
    - cmd: $HOME/.cargo/bin/cargo build --color=never
      images: ["debian"]
install:
  steps:
    - cmd: mkdir -p usr/bin
    - cmd: install -m755 $PKGER_BLD_DIR/target/debug/pkger usr/bin/

