[info]
name = "curl"
description = "curl"
vendor = ""
version = "7.67.0"
revision = "0"
source = "curl-7.67.0.tar.gz"
depends = ["gcc", "make", "patch", "binutils", "strace"]
# For now either redhat, centos, ubuntu or debian
exclude = ["usr/share/info/dir"]
images = [
	"ubuntu_latest",
	"centos",
]

[build]
steps = [
	#"./curl-7.67.0/configure --prefix=/opt/curl/7.67.0",
	#"make"
]

[install]
steps = []#"strace make install"]
destdir = "/tmp"
