[info]
name = "curl"
description = "curl"
vendor = ""
version = "7.67.0"
source = "curl-7.67.0.tar.gz"
depends = ["gcc", "make", "patch", "binutils"]
images = ["ubuntu:latest"]
exclude = ["usr/share/info/dir"]

[build]
steps = [
	"./curl-7.67.0/configure --prefix=/opt/curl/7.67.0",
	"make"
]

[install]
steps = [
	"make install"
]
