[package]
name = "pkger"
version = "0.0.1"
authors = ["wojciech.kepka <wojtek.kepka@protonmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/wojciechkepka/pkger"
repository = "https://github.com/wojciechkepka/pkger"
keywords = ["unix", "linux", "deb", "rpm", "build"]
description = "Building tool inspired by fpm-builder"
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wharf = { git = "https://github.com/wojciechkepka/wharf", branch = "master" }
log = "0.4.8"
failure = "0.1.6"
tokio = {version="0.2.4", features=["macros"]}
pretty_env_logger = "0.3.1"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"
tar = "0.4"
structopt = "0.3.7"
clap = "2.33.0"
