[info]
name = "curl"
description = "curl"
vendor = ""
arch = "x86_64"
license = "null"
version = "7.67.0"
revision = "0"
source = "curl-7.67.0.tar.gz"
depends = ["gcc", "make", "patch", "binutils", "strace"]
exclude = ["usr/share/info/dir"]
images = [
	"centos",
	"fedora",
	"ubuntu_latest",
]

[build]
steps = [
	"./curl-7.67.0/configure --prefix=/opt/curl/7.67.0",
	"make"
]

[install]
steps = ["make install"]
destdir = "/opt/curl/7.67.0"
