---
metadata:
  name: test-package
  version: 0.1.0
  description: pkger test package
  arch: x86_64
  license: MIT
  images: [ rocky, debian ]
configure:
  steps:
    - cmd: mkdir -p $PKGER_OUT_DIR/$RECIPE_VERSION/$RECIPE
build:
  working_dir: $PKGER_OUT_DIR/$RECIPE_VERSION/$RECIPE
  steps:
    - cmd: echo $PWD
install:
  steps:
    - cmd: mkdir -p $PKGER_OUT_DIR/test/deb
      images: ["debian"]
    - cmd: mkdir -p $PKGER_OUT_DIR/test/rpm
      images: ["rocky"]
    - cmd: echo "123" > $PKGER_OUT_DIR/test/rpm/test_file
      images: ["rocky"]
    - cmd: echo "321" > $PKGER_OUT_DIR/test/deb/test_file
      images: ["debian"]
