name: Pkger CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2-beta
      with:
        repository: 'wojciechkepka/pkger'
        ref: 'master'
      
    - name: Build
      run: cargo build --verbose
      
    - name: Run tests
      run: |
        sudo apt -y install docker
        sudo dockerd -H tcp://0.0.0.0:2376
        RUST_LOG=pkger=trace cargo run -- -d http://0.0.0.0:2376 -c example/conf.toml pkger

